version: '3'

services:
  db:
    container_name: ${CONTAINER_NAME}-db
    image: mysql:5.7.42
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  wordpress:
    container_name: ${CONTAINER_NAME}-host
    depends_on:
      - db
    image: wordpress:6.2.1-apache
    ports:
      - ${WORDPRESS_PORT}:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${WORDPRESS_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_PASSWORD}
    working_dir: /var/www/html
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
volumes:
  db_data:
